language: node_js
sudo: required
node_js: 8.2
install: npm install
before_script: npm install -g codeclimate-test-reporter
script:
- npm run test
after_script:
  codeclimate-test-reporter < coverage/**/lcov.info
addons:
  code_climate:
    repo_token: 57f4364f7f27d94e1c00cf839bc397f7a3d599c786520c229bac50a2b2490687
